# Generated by Django 4.2.6 on 2023-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(upload_to='media/uploaded_resumes/'),
        ),
    ]
