# Generated by Django 4.2.6 on 2023-11-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='created_by',
        ),
    ]
