# Generated by Django 4.2.6 on 2023-11-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_created_by_jobdescription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='user',
            new_name='created_by',
        ),
    ]
