# Generated by Django 4.2.6 on 2023-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_user_jobdescription_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
    ]
