# Generated by Django 4.2.7 on 2023-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
