# Generated by Django 4.2.7 on 2023-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('HR', 'HR')], default='User', max_length=10),
        ),
    ]
