# Generated by Django 4.2.7 on 2023-11-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer')], default='User', max_length=10),
        ),
    ]
